include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Additional project-specific rules
    public_member_api_docs: true
    lines_longer_than_80_chars: false
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  
  errors:
    invalid_annotation_target: ignore
