include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false

analyzer:
  errors:
    # Ignore path dependency warning for monorepo development
    invalid_dependency: ignore
